# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx_projects/gyro2tester/vivado/project/gyro2_tester.srcs/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_2/design_2_proc_sys_reset_0_2.xci
# IP: The module: 'design_2_proc_sys_reset_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx_projects/gyro2tester/vivado/project/gyro2_tester.gen/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_2/design_2_proc_sys_reset_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_proc_sys_reset_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx_projects/gyro2tester/vivado/project/gyro2_tester.gen/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_2/design_2_proc_sys_reset_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_proc_sys_reset_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx_projects/gyro2tester/vivado/project/gyro2_tester.gen/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_2/design_2_proc_sys_reset_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_proc_sys_reset_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Xilinx_projects/gyro2tester/vivado/project/gyro2_tester.srcs/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_2/design_2_proc_sys_reset_0_2.xci
# IP: The module: 'design_2_proc_sys_reset_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx_projects/gyro2tester/vivado/project/gyro2_tester.gen/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_2/design_2_proc_sys_reset_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_proc_sys_reset_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx_projects/gyro2tester/vivado/project/gyro2_tester.gen/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_2/design_2_proc_sys_reset_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_proc_sys_reset_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx_projects/gyro2tester/vivado/project/gyro2_tester.gen/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_2/design_2_proc_sys_reset_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_proc_sys_reset_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
