# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/gyro_constraints.xdc

# Block Designs: bd/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_processing_system7_0_0 || ORIG_REF_NAME==design_2_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_blk_mem_0_even_0/design_2_blk_mem_0_even_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_blk_mem_0_even_0 || ORIG_REF_NAME==design_2_blk_mem_0_even_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_blk_mem_0_odd_0/design_2_blk_mem_0_odd_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_blk_mem_0_odd_0 || ORIG_REF_NAME==design_2_blk_mem_0_odd_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_blk_mem_2_odd_0/design_2_blk_mem_2_odd_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_blk_mem_2_odd_0 || ORIG_REF_NAME==design_2_blk_mem_2_odd_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_blk_mem_1_even_1/design_2_blk_mem_1_even_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_blk_mem_1_even_1 || ORIG_REF_NAME==design_2_blk_mem_1_even_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_blk_mem_1_even_0/design_2_blk_mem_1_even_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_blk_mem_1_even_0 || ORIG_REF_NAME==design_2_blk_mem_1_even_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_blk_mem_0_even_1/design_2_blk_mem_0_even_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_blk_mem_0_even_1 || ORIG_REF_NAME==design_2_blk_mem_0_even_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_RxFIFO_0/design_2_RxFIFO_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_RxFIFO_0 || ORIG_REF_NAME==design_2_RxFIFO_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axis_switch_0_0/design_2_axis_switch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axis_switch_0_0 || ORIG_REF_NAME==design_2_axis_switch_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axis_switch_1_0/design_2_axis_switch_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axis_switch_1_0 || ORIG_REF_NAME==design_2_axis_switch_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_data_processor_0_0/design_2_data_processor_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_data_processor_0_0 || ORIG_REF_NAME==design_2_data_processor_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axis_switch_2_0/design_2_axis_switch_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axis_switch_2_0 || ORIG_REF_NAME==design_2_axis_switch_2_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axis_switch_3_0/design_2_axis_switch_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axis_switch_3_0 || ORIG_REF_NAME==design_2_axis_switch_3_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_proc_sys_reset_0_1/design_2_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_1 || ORIG_REF_NAME==design_2_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_proc_sys_reset_0_2/design_2_proc_sys_reset_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_2 || ORIG_REF_NAME==design_2_proc_sys_reset_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_SPI_ip_0_0/design_2_SPI_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_SPI_ip_0_0 || ORIG_REF_NAME==design_2_SPI_ip_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_iobuf_xil_0_0/design_2_iobuf_xil_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_iobuf_xil_0_0 || ORIG_REF_NAME==design_2_iobuf_xil_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_smartconnect_0_0/design_2_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_smartconnect_0_0 || ORIG_REF_NAME==design_2_smartconnect_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_dma_0_0/design_2_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_dma_0_0 || ORIG_REF_NAME==design_2_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconcat_1_0/design_2_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconcat_1_0 || ORIG_REF_NAME==design_2_xlconcat_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xbar_0/design_2_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xbar_0 || ORIG_REF_NAME==design_2_xbar_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ps7_0_axi_periph_0/design_2_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_blk0_mem_tx_odd_0/design_2_blk0_mem_tx_odd_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_blk0_mem_tx_odd_0 || ORIG_REF_NAME==design_2_blk0_mem_tx_odd_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_blk1_mem_tx_odd_0/design_2_blk1_mem_tx_odd_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_blk1_mem_tx_odd_0 || ORIG_REF_NAME==design_2_blk1_mem_tx_odd_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_blk_mem_1_even_2/design_2_blk_mem_1_even_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_blk_mem_1_even_2 || ORIG_REF_NAME==design_2_blk_mem_1_even_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_blk1_mem_tx_even_0/design_2_blk1_mem_tx_even_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_blk1_mem_tx_even_0 || ORIG_REF_NAME==design_2_blk1_mem_tx_even_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_blk2_mem_tx_even_0/design_2_blk2_mem_tx_even_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_blk2_mem_tx_even_0 || ORIG_REF_NAME==design_2_blk2_mem_tx_even_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_blk_mem_tx_even_0/design_2_blk_mem_tx_even_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_blk_mem_tx_even_0 || ORIG_REF_NAME==design_2_blk_mem_tx_even_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axis_stream_txfifo_0_2/design_2_axis_stream_txfifo_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axis_stream_txfifo_0_2 || ORIG_REF_NAME==design_2_axis_stream_txfifo_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_led_driver_0_0/design_2_led_driver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_led_driver_0_0 || ORIG_REF_NAME==design_2_led_driver_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_BiDirChannels_0_0/design_2_BiDirChannels_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_BiDirChannels_0_0 || ORIG_REF_NAME==design_2_BiDirChannels_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_auto_pc_0 || ORIG_REF_NAME==design_2_auto_pc_0} -quiet] -quiet

# XDC: /home/cdickins/reuse/gyro2tester-main/vivado/project/gyro2_tester.gen/sources_1/bd/design_2/design_2_ooc.xdc
